In [ ]:
import torch 
from torch.autograd import Variable

x = Variable(torch.Tensor(4, 4))
# x.data   x.grad

![](pytorchImage.png)

In [12]:
x.requires_grad = True
x.requires_grad

True

In [14]:
x1 = Variable(torch.ones(2, 2), requires_grad=True)
x1

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [33]:
y = x1 + 4
z = y*y*3
z

tensor([[75., 75.],
        [75., 75.]], grad_fn=<MulBackward0>)

In [34]:
out = z.mean()
out

tensor(75., grad_fn=<MeanBackward0>)

In [35]:
out.backward()

In [36]:
x1.grad

tensor([[12., 12.],
        [12., 12.]])